Share lightFactorUniforms
JiangYizhou/aquarium-test pull request #14
Opened 2019-04-11 02:59 UTC by JiangYizhou

LightFactorUniforms can be shared among multiple instances. These separate
instances use the same data for lightFactorUniforms, so we should instead
share a buffer between all instances of the same model. For example, the
uniform is the same to Rock, Ship and Coral.

This commit fixes #5

2019-04-11 16:38 UTC, bjjones requested changes
Thanks for putting this together. Unfortunately this isn't what I had in mind. What I was suggesting was sharing `LightFactorUniforms` on the GPU. This change only shares the data on the CPU.

To share on the GPU, you would not initialize `lightFactorBuffer` for every model instance. Instead you would call createBufferFromData once and share the same GPU-side buffer address between model instances when possible.

As a less robust alternative, I believe you could also remove lightFactorBuffer and instead hardcode the values into the fragment shaders for models that share values.

2019-04-19 22:54 UTC, bjjones commented
Yizhou - Sorry to go back and forth on this, but I think it may be better to leave lightFactorUniforms as is. I'm going to close the issue I opened. 

My initial thinking was that this would be an optimization for the workload, but thinking more I believe this will actually make the workload less representative of a real world scenario when individual draws are implemented. You can close this PR out.

2019-04-20 03:56 UTC, JiangYizhou commented
@bjjones I think this uniform buffer can be optimized and share between a same type of model. Are you considering a more heavy performance test? Do you mean the lightFactorUniforms may be different for every instance in real world scenario?

2019-04-20 03:57 UTC, closed without merging

2019-04-22 16:55 UTC, bjjones commented
Yes, I agree that the uniform buffer can be optimized from the perspective of optimizing the aquarium workload - but I think that optimizing the workload isn't really what we should do - instead we should attempt to model a real world application. 

I suggest we don't do this optimization because the primary feedback I have seen on the Aquarium is that we need to be able to draw individual instances of objects. Drawing individual instances better models a real world application because there are many different objects in a real world application. I'm thinking each of the instances of each model we draw should be as unique of an object as possible. 

Sharing this buffer would be optimal, but this is only possible because we make many instances of the same object - which doesn't reflect real-world scenarios in my opinion.

Do you agree?

2019-04-23 01:59 UTC, JiangYizhou commented
@bjjones Yes, this makes sense.